### ISSUE TITLE
Restliche GIF auch mit SVG ersetzen?

### ISSUE THREAD

**Issue by NinaG** [heimseiten/contao_3_5_backend_theme_flexible_c4#2]
Es gibt noch einige Icons die in diesem Theme weiterhin als GIF eingebunden sind, anstatt die neuen SVG zu nutzen (root, article, regular [Seitentypen], reload, die Minus-Plus-Icons etc.). Kannst du diese bitte auch umstellen?

**Comment by NinaG** [comment]
PS: Danke für deine bisherige Arbeit. Das ist schon sehr hilfreich!

**Comment by heimseiten** [comment]
Hallo Nina, würde ich gerne, leider konnte ich die in der dcaconfig.php notwendigen Einträge dazu nicht finden. Wenn Du diese Einträge, oder eine andere Lösung kennst, binde ich die gerne ein :)

**Comment by heimseiten** [comment]
Das "Theme" wurde nun etwas vereinfacht, sodass auf die Änderungen in der dcaconfig.php verzichtet werden kann. Der Austausch der Icons wird nun komplett über css gesteuert. Damit können nun wirklich alle Icons ausgetauscht werden.
